  [[redirects]]                                                                                             
    from = "/*"                                                                                             
    to = "https://manpage.dev/bryanmikaelian"                                                               
    status = 301                                                                                            
    force = true                                      
